# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: selivan.github.io
#email: selivan2@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Just another IT blog and some random stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://selivan.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  selivan

# Build settings
markdown: kramdown
gems:
  # RSS feeds
  - jekyll-feed
  # https://help.github.com/articles/redirects-on-github-pages/
  - jekyll-redirect-from
  # GitHub Emoji
  - jemoji
  # GitHub @mentions
  - jekyll-mentions

